// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"portfolio-api/ent/app"
	"portfolio-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (au *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetTitle sets the "title" field.
func (au *AppUpdate) SetTitle(s string) *AppUpdate {
	au.mutation.SetTitle(s)
	return au
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (au *AppUpdate) SetNillableTitle(s *string) *AppUpdate {
	if s != nil {
		au.SetTitle(*s)
	}
	return au
}

// SetDetail sets the "detail" field.
func (au *AppUpdate) SetDetail(s string) *AppUpdate {
	au.mutation.SetDetail(s)
	return au
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (au *AppUpdate) SetNillableDetail(s *string) *AppUpdate {
	if s != nil {
		au.SetDetail(*s)
	}
	return au
}

// SetLink sets the "link" field.
func (au *AppUpdate) SetLink(s string) *AppUpdate {
	au.mutation.SetLink(s)
	return au
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (au *AppUpdate) SetNillableLink(s *string) *AppUpdate {
	if s != nil {
		au.SetLink(*s)
	}
	return au
}

// SetLinkType sets the "link_type" field.
func (au *AppUpdate) SetLinkType(at app.LinkType) *AppUpdate {
	au.mutation.SetLinkType(at)
	return au
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (au *AppUpdate) SetNillableLinkType(at *app.LinkType) *AppUpdate {
	if at != nil {
		au.SetLinkType(*at)
	}
	return au
}

// SetImageURL sets the "image_url" field.
func (au *AppUpdate) SetImageURL(s string) *AppUpdate {
	au.mutation.SetImageURL(s)
	return au
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (au *AppUpdate) SetNillableImageURL(s *string) *AppUpdate {
	if s != nil {
		au.SetImageURL(*s)
	}
	return au
}

// Mutation returns the AppMutation object of the builder.
func (au *AppUpdate) Mutation() *AppMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AppUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AppUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AppUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AppUpdate) check() error {
	if v, ok := au.mutation.Title(); ok {
		if err := app.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "App.title": %w`, err)}
		}
	}
	if v, ok := au.mutation.Detail(); ok {
		if err := app.DetailValidator(v); err != nil {
			return &ValidationError{Name: "detail", err: fmt.Errorf(`ent: validator failed for field "App.detail": %w`, err)}
		}
	}
	if v, ok := au.mutation.Link(); ok {
		if err := app.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "App.link": %w`, err)}
		}
	}
	if v, ok := au.mutation.LinkType(); ok {
		if err := app.LinkTypeValidator(v); err != nil {
			return &ValidationError{Name: "link_type", err: fmt.Errorf(`ent: validator failed for field "App.link_type": %w`, err)}
		}
	}
	if v, ok := au.mutation.ImageURL(); ok {
		if err := app.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "App.image_url": %w`, err)}
		}
	}
	return nil
}

func (au *AppUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Title(); ok {
		_spec.SetField(app.FieldTitle, field.TypeString, value)
	}
	if value, ok := au.mutation.Detail(); ok {
		_spec.SetField(app.FieldDetail, field.TypeString, value)
	}
	if value, ok := au.mutation.Link(); ok {
		_spec.SetField(app.FieldLink, field.TypeString, value)
	}
	if value, ok := au.mutation.LinkType(); ok {
		_spec.SetField(app.FieldLinkType, field.TypeEnum, value)
	}
	if value, ok := au.mutation.ImageURL(); ok {
		_spec.SetField(app.FieldImageURL, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetTitle sets the "title" field.
func (auo *AppUpdateOne) SetTitle(s string) *AppUpdateOne {
	auo.mutation.SetTitle(s)
	return auo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (auo *AppUpdateOne) SetNillableTitle(s *string) *AppUpdateOne {
	if s != nil {
		auo.SetTitle(*s)
	}
	return auo
}

// SetDetail sets the "detail" field.
func (auo *AppUpdateOne) SetDetail(s string) *AppUpdateOne {
	auo.mutation.SetDetail(s)
	return auo
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (auo *AppUpdateOne) SetNillableDetail(s *string) *AppUpdateOne {
	if s != nil {
		auo.SetDetail(*s)
	}
	return auo
}

// SetLink sets the "link" field.
func (auo *AppUpdateOne) SetLink(s string) *AppUpdateOne {
	auo.mutation.SetLink(s)
	return auo
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (auo *AppUpdateOne) SetNillableLink(s *string) *AppUpdateOne {
	if s != nil {
		auo.SetLink(*s)
	}
	return auo
}

// SetLinkType sets the "link_type" field.
func (auo *AppUpdateOne) SetLinkType(at app.LinkType) *AppUpdateOne {
	auo.mutation.SetLinkType(at)
	return auo
}

// SetNillableLinkType sets the "link_type" field if the given value is not nil.
func (auo *AppUpdateOne) SetNillableLinkType(at *app.LinkType) *AppUpdateOne {
	if at != nil {
		auo.SetLinkType(*at)
	}
	return auo
}

// SetImageURL sets the "image_url" field.
func (auo *AppUpdateOne) SetImageURL(s string) *AppUpdateOne {
	auo.mutation.SetImageURL(s)
	return auo
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (auo *AppUpdateOne) SetNillableImageURL(s *string) *AppUpdateOne {
	if s != nil {
		auo.SetImageURL(*s)
	}
	return auo
}

// Mutation returns the AppMutation object of the builder.
func (auo *AppUpdateOne) Mutation() *AppMutation {
	return auo.mutation
}

// Where appends a list predicates to the AppUpdate builder.
func (auo *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated App entity.
func (auo *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AppUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AppUpdateOne) check() error {
	if v, ok := auo.mutation.Title(); ok {
		if err := app.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "App.title": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Detail(); ok {
		if err := app.DetailValidator(v); err != nil {
			return &ValidationError{Name: "detail", err: fmt.Errorf(`ent: validator failed for field "App.detail": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Link(); ok {
		if err := app.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "App.link": %w`, err)}
		}
	}
	if v, ok := auo.mutation.LinkType(); ok {
		if err := app.LinkTypeValidator(v); err != nil {
			return &ValidationError{Name: "link_type", err: fmt.Errorf(`ent: validator failed for field "App.link_type": %w`, err)}
		}
	}
	if v, ok := auo.mutation.ImageURL(); ok {
		if err := app.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "App.image_url": %w`, err)}
		}
	}
	return nil
}

func (auo *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Title(); ok {
		_spec.SetField(app.FieldTitle, field.TypeString, value)
	}
	if value, ok := auo.mutation.Detail(); ok {
		_spec.SetField(app.FieldDetail, field.TypeString, value)
	}
	if value, ok := auo.mutation.Link(); ok {
		_spec.SetField(app.FieldLink, field.TypeString, value)
	}
	if value, ok := auo.mutation.LinkType(); ok {
		_spec.SetField(app.FieldLinkType, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.ImageURL(); ok {
		_spec.SetField(app.FieldImageURL, field.TypeString, value)
	}
	_node = &App{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
