// Code generated by ent, DO NOT EDIT.

package ent

import (
	"portfolio-api/ent/app"
)

// CreateAppInput represents a mutation input for creating apps.
type CreateAppInput struct {
	Title    string
	Detail   string
	Link     string
	LinkType app.LinkType
	ImageURL string
}

// Mutate applies the CreateAppInput on the AppMutation builder.
func (i *CreateAppInput) Mutate(m *AppMutation) {
	m.SetTitle(i.Title)
	m.SetDetail(i.Detail)
	m.SetLink(i.Link)
	m.SetLinkType(i.LinkType)
	m.SetImageURL(i.ImageURL)
}

// SetInput applies the change-set in the CreateAppInput on the AppCreate builder.
func (c *AppCreate) SetInput(i CreateAppInput) *AppCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateAppInput represents a mutation input for updating apps.
type UpdateAppInput struct {
	Title    *string
	Detail   *string
	Link     *string
	LinkType *app.LinkType
	ImageURL *string
}

// Mutate applies the UpdateAppInput on the AppMutation builder.
func (i *UpdateAppInput) Mutate(m *AppMutation) {
	if v := i.Title; v != nil {
		m.SetTitle(*v)
	}
	if v := i.Detail; v != nil {
		m.SetDetail(*v)
	}
	if v := i.Link; v != nil {
		m.SetLink(*v)
	}
	if v := i.LinkType; v != nil {
		m.SetLinkType(*v)
	}
	if v := i.ImageURL; v != nil {
		m.SetImageURL(*v)
	}
}

// SetInput applies the change-set in the UpdateAppInput on the AppUpdate builder.
func (c *AppUpdate) SetInput(i UpdateAppInput) *AppUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateAppInput on the AppUpdateOne builder.
func (c *AppUpdateOne) SetInput(i UpdateAppInput) *AppUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
