// Code generated by ent, DO NOT EDIT.

package ent

import (
	"portfolio-api/ent/company"
	"portfolio-api/ent/schema"
	"portfolio-api/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescTitle is the schema descriptor for title field.
	companyDescTitle := companyFields[1].Descriptor()
	// company.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	company.TitleValidator = companyDescTitle.Validators[0].(func(string) error)
	// companyDescDetail is the schema descriptor for detail field.
	companyDescDetail := companyFields[2].Descriptor()
	// company.DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	company.DetailValidator = companyDescDetail.Validators[0].(func(string) error)
	// companyDescLink is the schema descriptor for link field.
	companyDescLink := companyFields[3].Descriptor()
	// company.LinkValidator is a validator for the "link" field. It is called by the builders before save.
	company.LinkValidator = companyDescLink.Validators[0].(func(string) error)
	// companyDescImageURL is the schema descriptor for image_url field.
	companyDescImageURL := companyFields[5].Descriptor()
	// company.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	company.ImageURLValidator = companyDescImageURL.Validators[0].(func(string) error)
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
