package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"portfolio-api/ent"
	"portfolio-api/utils/errCustom"
	"portfolio-api/utils/validation"

	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (uuid.UUID, error) {
	// TODO: email and password validation
	isInvalid := validation.Email(input.Email)
	if isInvalid {
		return uuid.Nil, errCustom.Create("Invalid email")
	}
	user, err := r.client.User.Create().SetInput(input).Save(ctx)
	return user.ID, err
}
