name: api ci

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Generate Go code
        run: make gen

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test-go
