name: api ci

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # REF: https://github.com/actions/setup-go
          # NOTE: Due to the peculiarities of YAML parsing, it is recommended to wrap the version in single quotation marks:
          go-version: "1.23.2"

      - name: Generate Go code
        run: make gen

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test-go
