name: client ci

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: client

jobs:
  install:
    runs-on: ubuntu-latest

    # REF: https://github.com/google-github-actions/auth?tab=readme-ov-file#usage
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      # https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}


      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Install dependencies
        run: pnpm install

      - name: Spellcheck
        run: pnpm spellcheck

      - name: Lint
        run: pnpm eslint

      - name: Interface
        run: pnpm interface

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
