name: client ci

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: client

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Install dependencies
        run: pnpm install

      - name: Spellcheck
        run: pnpm spellcheck

      - name: Lint
        run: pnpm eslint

      - name: Create .env file
        run: |
          echo "VITE_GRAPHQL_SCHEMA_URL=${{ secrets.VITE_GRAPHQL_SCHEMA_URL }}" >> .env

      - name: Build
        run: pnpm build

      - name: Remove .env file
        run: rm .env

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
